### ISSUE TITLE
Debugging undercover errors 

### ISSUE THREAD

**Issue by cpitclaudel** [undercover-el/undercover.el#17]
Hi,

I'm seeing a few inconsistencies in the way coverage is calculated; what's the general approach to tracking/debugging them?

For a concrete example: https://coveralls.io/builds/5522334/source?filename=biblio-crossref.el#L94 calls https://coveralls.io/builds/5522334/source?filename=biblio-core.el#L698, but the second one is shown as having never run, while the first one did run. The second one is the only caller of https://coveralls.io/builds/5522334/source?filename=biblio-core.el#L688, which is shown as having run.

There is no interceptions of redefinitions going on in that part of my testing code, either.

Cheers,
Clément.

**Comment by sviridov** [comment]
Hi,

sorry it took so long to answer you.

> what's the general approach to tracking/debugging them?

I'm afraid it's quite hard right now. `undercover.el` heavily relies on `edebug` and it's so-called `stop points`. So it can be actually `edebug` issue. I will investigate it more.

**Comment by cpitclaudel** [comment]
Thanks for the reply. It seems that the problem arises for functions that have an interactive spec; I've seen the problem occur only with those, even when they *are* called non-interactively.

**Comment by cpitclaudel** [comment]
Another issues that might be related: coveralls report 101% coverage for one of the files [here](https://coveralls.io/builds/5557120); could this be related to undercover.el?

**Comment by sviridov** [comment]
> Another issues that might be related: coveralls report 101% coverage for one of the files here; could this be related to undercover.el?

I think it's `coveralls` bug. `undercover.el` sends only absolute numbers for every file line.

**Comment by CyberShadow** [comment]
Hi, this issue is quite old and I don't see a way to get to a reproducible test case from here right now, so I'm going to close this; but, if you do still have a way to reproduce this problem, please leave a comment and we can reopen and look into it.

For the 101% case it would be helpful if you could post the JSON report that undercover.el uploads to Coveralls (saved to `/tmp/undercover_coveralls_report` by default), and we could look to see if there's anything wrong with it.

 Thanks!
