### ISSUE TITLE
Ignoring a directory should ignore everything inside it and all subdirectories

### ISSUE THREAD

**Issue by DarwinAwardWinner** [undercover-el/undercover.el#56]
Currently, it seems that undercover can only be told to ignore specific files. It would be nice if I could specify a directory as an ignore pattern and have it ignore everything in that directory and all its subdirectories. You could also use the somewhat standard double asterisk notation for this, e.g. `some_dir/**` to recursively ignore everything in some_dir.

**Comment by CyberShadow** [comment]
Undercover uses `file-expand-wildcards` to expand wildcards, both for inclusions and exclusions. Note that exclusions don't work like ignores: `:exclude` masks are still globbed for, but then added to a set that is then subtracted from the included files.

A request to ignore everything in a directory and its subdirectories therefore doesn't make sense to me, because there is no way to *include* everything in a directory and its subdirectories.

If you could post a practical example of what you're trying to achieve and the problem you're encountering, that would give us a better picture of where we are and where we want to be.

**Comment by DarwinAwardWinner** [comment]
I honestly can't remember what I was trying to do, but whatever it was, I think Eldev now handles it automatically.

**Comment by CyberShadow** [comment]
OK, no problem. Let's close this for now, and if the issue becomes clearer in the future, we can always reopen.
